#!/usr/bin/env bun
// Generate docs/rules.md from the rule catalog, so the docs and SARIF help links never drift from the code.
//   bun scripts/gen-rules-doc.ts          write docs/rules.md
//   bun scripts/gen-rules-doc.ts --check  exit 1 if docs/rules.md is out of date (for CI)
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { RuleMeta } from "../src/core/rule";
import { CATEGORIES } from "../src/core/types";
import { ruleAnchor } from "../src/report/sarif";
import { knownRules } from "../src/report/shared";

const DOC = fileURLToPath(new URL("../docs/rules.md", import.meta.url));

const INTRO = `# Rules

<!-- Generated by scripts/gen-rules-doc.ts from the rule catalog. Do not edit by hand: run \`bun run docs:rules\`. -->

skill-scanner reads every file of a skill (SKILL.md, references, scripts, manifests) and checks it
against the rules below. \`skill-scanner rules\` prints the same list in the terminal.

## How findings become a verdict

Each rule has a default **severity** (info, low, medium, high, critical) and a **confidence**
(low, medium, high) that its match means what it says. A rule may raise or lower the severity of a
single match, for example when a command sits in a README that agents rarely load.

- A finding's *effective severity* is its severity, one level lower when its confidence is low.
  A hunch alone never blocks, but it still shows up as a warning.
- A skill is **blocked** when any finding's effective severity is \`high\` or more, and gets a
  **warning** at \`medium\`. Change the thresholds with \`blockAt\` and \`warnAt\` in
  \`~/.skill-scanner/config.json\`.
- Rules marked **hard** report concrete evidence. The optional jev judge can confirm them but never
  doubt them. For other findings the judge's opinion is shown next to the finding.

## Suppressing a finding

Read the finding and the file first. If the skill is fine, approve that exact version:

    skill-scanner trust <path>

Trust is tied to the skill's digest, so any change to the skill is scanned again. To silence a rule
instead, add an \`ignore\` entry to \`~/.skill-scanner/config.json\`:

\`\`\`json
{
  "ignore": [
    { "rule": "network/suspicious-endpoint", "path": "scripts/**", "reason": "reviewed: posts to our own API" }
  ]
}
\`\`\`

\`rule\` is a rule id or \`category/*\`. \`path\` is an optional glob over finding paths. \`digest\`
(\`sha256:...\`, shown in JSON output) limits the entry to one version of one skill. Configuration is
only read from your home directory or \`--config\`, never from the directory being scanned.
`;

function ruleSection(r: RuleMeta): string {
  const facts = [`Severity: ${r.severity}.`, `Confidence: ${r.confidence}.`];
  if (r.hard) facts.push("Hard: the jev judge can confirm but never doubt it.");
  const lines = [`<a name="${ruleAnchor(r.id)}"></a>`, "", `### ${r.id}`, "", `**${r.title}**`, "", facts.join(" "), "", r.description, ""];
  if (r.remediation) lines.push(`Remediation: ${r.remediation}`, "");
  return lines.join("\n");
}

export function renderRulesDoc(rules: readonly RuleMeta[]): string {
  const groups = CATEGORIES.map((c) => [c, rules.filter((r) => r.category === c)] as const).filter(([, rs]) => rs.length > 0);
  const toc = groups.map(([c, rs]) => `- [${c}](#${c}) (${rs.length})`);
  const sections = groups.map(([c, rs]) => [`## ${c}`, "", ...rs.map(ruleSection)].join("\n"));
  return `${[INTRO, "## Categories", "", ...toc, "", ...sections].join("\n").trimEnd()}\n`;
}

async function readExisting(): Promise<string | undefined> {
  try {
    return await readFile(DOC, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw e;
  }
}

async function main(argv: readonly string[]): Promise<number> {
  const unknown = argv.filter((a) => a !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`gen-rules-doc: unknown argument ${unknown[0]}\n`);
    return 2;
  }
  const next = renderRulesDoc(knownRules());
  const current = await readExisting();
  if (argv.includes("--check")) {
    if (current === next) return 0;
    process.stderr.write("docs/rules.md is out of date. Run `bun run docs:rules` and commit the result.\n");
    return 1;
  }
  if (current !== next) {
    await mkdir(dirname(DOC), { recursive: true });
    await writeFile(DOC, next);
  }
  process.stdout.write(`docs/rules.md: ${knownRules().length} rules${current === next ? " (unchanged)" : ""}\n`);
  return 0;
}

if (import.meta.main) {
  main(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (e: unknown) => {
      process.stderr.write(`gen-rules-doc: ${e instanceof Error ? e.message : String(e)}\n`);
      process.exitCode = 2;
    },
  );
}
